### ISSUE TITLE
get rid of deprecated gtk symbols (was: mp3splt-gtk-0.9 build fails on fedora 20)

### ISSUE THREAD

**Issue by mp3splt** [mp3splt/mp3splt#297]
Imported from SourceForge on 2020-09-13 16:51:38
Created by **[*anonymous](https://sourceforge.net/u/*anonymous/)** on 2014-04-05 14:43:15
Original: https://sourceforge.net/p/mp3splt/bugs/165

---

In file included from all_includes.h:38:0,
                 from splitpoints_window.h:41,
                 from splitpoints_window.c:40:
ui_types.h:205:3: error: unknown type name ‘GtkActionGroup’
   GtkActionGroup *action_group;
   ^
splitpoints_window.c: In function ‘create_trim_silence_window’:
splitpoints_window.c:1137:9: error: ‘GTK_STOCK_OK’ undeclared (first use in this function)
         GTK_STOCK_OK,
         ^
splitpoints_window.c:1137:9: note: each undeclared identifier is reported only once for each function it appears in
splitpoints_window.c:1139:9: error: ‘GTK_STOCK_CANCEL’ undeclared (first use in this function)
         GTK_STOCK_CANCEL,
         ^
splitpoints_window.c: In function ‘create_detect_silence_and_add_splitpoints_window’:
splitpoints_window.c:1196:9: error: ‘GTK_STOCK_OK’ undeclared (first use in this function)
         GTK_STOCK_OK,
         ^
splitpoints_window.c:1198:9: error: ‘GTK_STOCK_CANCEL’ undeclared (first use in this function)
         GTK_STOCK_CANCEL,
         ^
splitpoints_window.c: In function ‘create_init_spinners_buttons’:
splitpoints_window.c:1436:49: error: ‘GTK_STOCK_ADD’ undeclared (first use in this function)
   GtkWidget *add_button = wh_create_cool_button(GTK_STOCK_ADD, _("_Add"), FALSE);
                                                 ^
splitpoints_window.c:1446:56: error: ‘GTK_STOCK_REMOVE’ undeclared (first use in this function)
   GtkWidget *remove_row_button = wh_create_cool_button(GTK_STOCK_REMOVE, _("_Remove"), FALSE);
                                                        ^
splitpoints_window.c:1456:56: error: ‘GTK_STOCK_CLEAR’ undeclared (first use in this function)
   GtkWidget *remove_all_button = wh_create_cool_button(GTK_STOCK_CLEAR, _("R_emove all"), FALSE);
                                                        ^
splitpoints_window.c: In function ‘create_init_special_buttons’:
splitpoints_window.c:1473:27: error: ‘GTK_STOCK_CUT’ undeclared (first use in this function)
     wh_create_cool_button(GTK_STOCK_CUT, _("_Trim splitpoints"), FALSE);
                           ^
splitpoints_window.c:1483:27: error: ‘GTK_STOCK_FIND_AND_REPLACE’ undeclared (first use in this function)
     wh_create_cool_button(GTK_STOCK_FIND_AND_REPLACE, _("_Silence detection"), FALSE);
                           ^
splitpoints_window.c: In function ‘build_and_show_popup_menu’:
splitpoints_window.c:1824:21: warning: initialization makes pointer from integer without a cast [enabled by default]
   GtkWidget *item = gtk_image_menu_item_new_with_label(_("Clone all tags"));
                     ^
splitpoints_window.c:1825:3: warning: ‘gtk_image_new_from_stock’ is deprecated (declared at /usr/include/gtk-3.0/gtk/gtkimage.h:123): Use 'gtk_image_new_from_icon_name' instead [-Wdeprecated-declarations]
   GtkWidget *image = gtk_image_new_from_stock(GTK_STOCK_COPY, GTK_ICON_SIZE_MENU);
   ^
splitpoints_window.c:1825:47: error: ‘GTK_STOCK_COPY’ undeclared (first use in this function)
   GtkWidget *image = gtk_image_new_from_stock(GTK_STOCK_COPY, GTK_ICON_SIZE_MENU);
                                               ^
splitpoints_window.c:1832:8: warning: assignment makes pointer from integer without a cast [enabled by default]
   item = gtk_image_menu_item_new_with_label(_("Clone title"));
        ^
splitpoints_window.c:1833:3: warning: ‘gtk_image_new_from_stock’ is deprecated (declared at /usr/include/gtk-3.0/gtk/gtkimage.h:123): Use 'gtk_image_new_from_icon_name' instead [-Wdeprecated-declarations]
   image = gtk_image_new_from_stock(GTK_STOCK_COPY, GTK_ICON_SIZE_MENU);
   ^
splitpoints_window.c:1838:8: warning: assignment makes pointer from integer without a cast [enabled by default]
   item = gtk_image_menu_item_new_with_label(_("Clone artist"));
        ^
splitpoints_window.c:1839:3: warning: ‘gtk_image_new_from_stock’ is deprecated (declared at /usr/include/gtk-3.0/gtk/gtkimage.h:123): Use 'gtk_image_new_from_icon_name' instead [-Wdeprecated-declarations]
   image = gtk_image_new_from_stock(GTK_STOCK_COPY, GTK_ICON_SIZE_MENU);
   ^
splitpoints_window.c:1844:8: warning: assignment makes pointer from integer without a cast [enabled by default]
   item = gtk_image_menu_item_new_with_label(_("Clone album"));
        ^
splitpoints_window.c:1845:3: warning: ‘gtk_image_new_from_stock’ is deprecated (declared at /usr/include/gtk-3.0/gtk/gtkimage.h:123): Use 'gtk_image_new_from_icon_name' instead [-Wdeprecated-declarations]
   image = gtk_image_new_from_stock(GTK_STOCK_COPY, GTK_ICON_SIZE_MENU);
   ^
splitpoints_window.c:1850:8: warning: assignment makes pointer from integer without a cast [enabled by default]
   item = gtk_image_menu_item_new_with_label(_("Clone genre"));
        ^
splitpoints_window.c:1851:3: warning: ‘gtk_image_new_from_stock’ is deprecated (declared at /usr/include/gtk-3.0/gtk/gtkimage.h:123): Use 'gtk_image_new_from_icon_name' instead [-Wdeprecated-declarations]
   image = gtk_image_new_from_stock(GTK_STOCK_COPY, GTK_ICON_SIZE_MENU);
   ^
splitpoints_window.c:1856:8: warning: assignment makes pointer from integer without a cast [enabled by default]
   item = gtk_image_menu_item_new_with_label(_("Clone year"));
        ^
splitpoints_window.c:1857:3: warning: ‘gtk_image_new_from_stock’ is deprecated (declared at /usr/include/gtk-3.0/gtk/gtkimage.h:123): Use 'gtk_image_new_from_icon_name' instead [-Wdeprecated-declarations]
   image = gtk_image_new_from_stock(GTK_STOCK_COPY, GTK_ICON_SIZE_MENU);
   ^
splitpoints_window.c:1862:8: warning: assignment makes pointer from integer without a cast [enabled by default]
   item = gtk_image_menu_item_new_with_label(_("Clone track"));
        ^
splitpoints_window.c:1863:3: warning: ‘gtk_image_new_from_stock’ is deprecated (declared at /usr/include/gtk-3.0/gtk/gtkimage.h:123): Use 'gtk_image_new_from_icon_name' instead [-Wdeprecated-declarations]
   image = gtk_image_new_from_stock(GTK_STOCK_COPY, GTK_ICON_SIZE_MENU);
   ^
splitpoints_window.c:1868:8: warning: assignment makes pointer from integer without a cast [enabled by default]
   item = gtk_image_menu_item_new_with_label(_("Clone comment"));
        ^
splitpoints_window.c:1869:3: warning: ‘gtk_image_new_from_stock’ is deprecated (declared at /usr/include/gtk-3.0/gtk/gtkimage.h:123): Use 'gtk_image_new_from_icon_name' instead [-Wdeprecated-declarations]
   image = gtk_image_new_from_stock(GTK_STOCK_COPY, GTK_ICON_SIZE_MENU);
   ^
splitpoints_window.c:1876:8: warning: assignment makes pointer from integer without a cast [enabled by default]
   item = gtk_image_menu_item_new_with_label(_("Auto-increment track"));
        ^
splitpoints_window.c:1877:3: warning: ‘gtk_image_new_from_stock’ is deprecated (declared at /usr/include/gtk-3.0/gtk/gtkimage.h:123): Use 'gtk_image_new_from_icon_name' instead [-Wdeprecated-declarations]
   image = gtk_image_new_from_stock(GTK_STOCK_GO_DOWN, GTK_ICON_SIZE_MENU);
   ^
splitpoints_window.c:1877:36: error: ‘GTK_STOCK_GO_DOWN’ undeclared (first use in this function)
   image = gtk_image_new_from_stock(GTK_STOCK_GO_DOWN, GTK_ICON_SIZE_MENU);
                                    ^
splitpoints_window.c: In function ‘create_columns’:
splitpoints_window.c:1992:42: error: ‘GTK_STOCK_MEDIA_PLAY’ undeclared (first use in this function)
   g_object_set(renderer_pix, "stock-id", GTK_STOCK_MEDIA_PLAY,
                                          ^
make[2]: *** [splitpoints_window.o] Error 1
make[2]: Leaving directory `/home/cb/Downloads/mp3splt-gtk-0.9/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/cb/Downloads/mp3splt-gtk-0.9'
make: *** [all] Error 2

**Comment by mp3splt** [comment]
Imported from SourceForge on 2020-09-13 16:51:40
Created by **[io_alex_2004](https://sourceforge.net/u/io_alex_2004/)** on 2014-04-20 22:13:29
Original: https://sourceforge.net/p/mp3splt/bugs/165/#b5eb

---

Hello,

Sorry for the late reply. I was quite busy.
What version of Fedora do you have ?
Do you know what version of GTK do you have ?

Thank you.

-- 
Alex

**Comment by mp3splt** [comment]
Imported from SourceForge on 2020-09-13 16:51:42
Created by **[*anonymous](https://sourceforge.net/u/*anonymous/)** on 2014-05-01 05:22:49
Original: https://sourceforge.net/p/mp3splt/bugs/165/#fe44

---

I'm seeing very similar build errors on a Gentoo system using GTK+ 3.10.8, but it builds fine using 2.24.23 (with --disable-gtk3)

**Comment by mp3splt** [comment]
Imported from SourceForge on 2020-09-13 16:51:50
Created by **[io_alex_2004](https://sourceforge.net/u/io_alex_2004/)** on 2014-05-01 09:04:36
Original: https://sourceforge.net/p/mp3splt/bugs/165/#b783

---

Hello,

I am working on fixing this issue.
Meanwhile, it should be enough to remove the following part
*-DGDK_DISABLE_DEPRECATED -DGTK_DISABLE_DEPRECATED*
from **configure.ac**

-- 
Alex

**Comment by mp3splt** [comment]
Imported from SourceForge on 2020-09-13 16:51:57
Created by **[io_alex_2004](https://sourceforge.net/u/io_alex_2004/)** on 2014-05-02 22:59:42
Original: https://sourceforge.net/p/mp3splt/bugs/165/#c70c

---

Hello,

I have just released the 0.9.1 version allowing deprecated symbols.
This version should compile fine.
Don't forget to compile libmp3splt 0.9.1 first.

-- 
Alex

**Comment by mp3splt** [comment]
Imported from SourceForge on 2020-09-13 16:52:09
Created by **[*anonymous](https://sourceforge.net/u/*anonymous/)** on 2014-05-04 15:45:44
Original: https://sourceforge.net/p/mp3splt/bugs/165/#9ce5

---

The problem is gone now. This issue can be closed.

**Comment by mp3splt** [comment]
Imported from SourceForge on 2020-09-13 16:52:20
Created by **[io_alex_2004](https://sourceforge.net/u/io_alex_2004/)** on 2014-05-06 21:34:03
Original: https://sourceforge.net/p/mp3splt/bugs/165/#fa41

---

- **summary**: mp3splt-gtk-0.9 build fails on fedora 20 --> get rid of deprecated gtk symbols (was: mp3splt-gtk-0.9 build fails on fedora 20)

**Comment by mp3splt** [comment]
Imported from SourceForge on 2020-09-13 16:52:26
Created by **[io_alex_2004](https://sourceforge.net/u/io_alex_2004/)** on 2014-05-08 21:49:12
Original: https://sourceforge.net/p/mp3splt/bugs/165/#5457

---

Deprecated symbols have been removed in the latest trunk version:
https://sourceforge.net/p/mp3splt/code/1440/

I am closing the ticket.
Please post here if still necessary.

**Comment by mp3splt** [comment]
Imported from SourceForge on 2020-09-13 16:52:39
Created by **[io_alex_2004](https://sourceforge.net/u/io_alex_2004/)** on 2014-05-08 21:49:27
Original: https://sourceforge.net/p/mp3splt/bugs/165/#56c9

---

- **status**: open --> closed

**Comment by mp3splt** [comment]
Imported from SourceForge on 2020-09-13 16:52:46
Created by **[*anonymous](https://sourceforge.net/u/*anonymous/)** on 2014-06-21 14:44:10
Original: https://sourceforge.net/p/mp3splt/bugs/165/#c70c/4c87

---

thanks
